name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: SeedPacketGenerator  # Replace with your App Service name
  AZURE_WEBAPP_PACKAGE_PATH: './publish'     # Path where the deployment expects the published app
  DOTNET_VERSION: '9.0.x'                    # Your .NET version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up .NET
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Build the app
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Publish the app to the ./publish folder
      - name: Publish with dotnet
        run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Debug: List files in the publish folder to confirm output
      - name: List files in publish folder
        run: ls -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}